### PR TITLE
X01BD: Initial build (Caf-edition) also different maintainer

### PR DESCRIPTION
**Pull request by Jayant-Deshmukh**

### CODE REVIEW

**Comment by Subinsmani** [comment]
@Jayant-Deshmukh You Uploaded the build?🤔

**Comment by Jayant-Deshmukh** [comment]
I don't have the keys for it! Or shall i take it from the other maintainer? I thought had a seperate folder for caf builds so waiting for approval and further instructions! @Subinsmani

**Comment by Subinsmani** [comment]
@Jayant-Deshmukh as of now don't need build/X01BD.json and changelog...
just add ur details to device.json only...

**Comment by Subinsmani** [comment]
@Jayant-Deshmukh then pm to @jhenrique09, after pr merge u will get upload details... then upload it to server then need device/X01BD.json and changelog..😂

**Comment by Jayant-Deshmukh** [comment]
Okok I'll close the PR then! @Subinsmani Ya i have messaged him abt the thing!

**Pull request closed without merging**
