### PR TITLE
Add new json

### PR DESCRIPTION
**Pull request by schneider94**

### CODE REVIEW

**Comment by andersonmendess** [comment]
@ErrorNetwork28 Wut

**Comment by Subinsmani** [comment]
What is this???

**Comment by Hlcpereira** [comment]
@ErrorNetwork28 Wtf?

**Comment by schneider94** [comment]
@jhenrique09 asked to open pull request

**Comment by Subinsmani** [comment]
@ErrorNetwork28 what is purpose of this PR???

**Comment by Hasaber8** [comment]
@ErrorNetwork28 Wtf are you even here?

**Pull request closed without merging**
