### PR TITLE
lavender: Update XDA threads

### PR DESCRIPTION
**Pull request by nunocodex**

### CODE REVIEW

**Comment by baalajimaestro** [comment]
This is Pixel CI Automation Service! This PR has been closed as it doesnt pass through our checks. You can check the Build Status under Semaphore CI to see where it failed.

**Comment by shreejoy** [comment]
This automation CI service is under WIP, Considering that I am reopening and merging the pull request.

**Comment by baalajimaestro** [comment]
This is Pixel CI Automation Service! This PR has been closed as it doesnt pass through our checks. You can check the Build Status under Semaphore CI to see where it failed.

**Comment by baalajimaestro** [comment]
> This automation CI service is under WIP, Considering that I am reopening and merging the pull request.

Lmfao. My usual derp.

**Pull request merged**
