### PR TITLE
Add Xiaomi Mi Pad 4

### PR DESCRIPTION
**Pull request by ghost**
to be official

### CODE REVIEW

**Comment by Hlcpereira** [comment]
Good day/afternoon/night.

Thanks for applying, but sadly your application is being rejected. I must say that the only problem with it, it's with your device trees, more especifically with the commit history of them. Also, if you can take any kind of advantage in using the already existent device_xiaomi_sdm660-common in our org for the devices sources repos, please do it, it will be better in someway or other. 

Once those are solved, you can apply once again.

Best regards,
Hlcpereira

**Comment by ghost** [comment]
I'll try building with your device_xiaomi_sdm660-common.

**Comment by ghost** [comment]
I succeeded in building ROM with your android_device_xiaomi_sdm660-common
and no bugs found at now. is's OK to use your device tree but I can no
longer submit maintainer form.

**Comment by shreejoy** [comment]
@mamarama9904 Maintainer ship form has to be filled once and if you want edit you responses just comment in pr with new data

**Comment by ghost** [comment]
I sent a pull request. please check info.

**Pull request closed without merging**
