### PR TITLE
Change maintainer of sanders

### PR DESCRIPTION
**Pull request by Jorg3Lucas**

### CODE REVIEW

**Comment by andersonmendess** [comment]
@jorgelucasd00 Lol

**Comment by Jorg3Lucas** [comment]
Pixel Experience Unofficial 9.0

Build Date: 20190209

Changelog:
> Feb Patch
> VoLTE Work
> DTV Work to Brazillian Users
> DTV Removed to Non-brazillian Users
> Last Sources
> Rádio FM Work

**Comment by andersonmendess** [comment]
@jorgelucasd00 Stable af & bugless & lag free

**Comment by Jorg3Lucas** [comment]
> @jorgelucasd00 Stable af & bugless & lag free

yes

**Comment by yashsonawane** [comment]
@andersonmendess Don't accept

**Pull request merged**
