### PR TITLE
Add MI 8 SE suppport

### PR DESCRIPTION
**Pull request by etylix**
These trees just uploaded few minutes ago because i'm lazy to commit 😂😂
And i'm use modified sdm710-common tree because sirius don't have FOD

### CODE REVIEW

**Comment by Hlcpereira** [comment]
@etylix FOD is been built for sirius or anything related with it giving errors while building for sirius?

**Comment by etylix** [comment]
Yes

**Comment by etylix** [comment]
It had some errors when building with FOD

**Comment by Hlcpereira** [comment]
@etylix PM me on telegram with the log of the error, guess I already know what to do

**Comment by etylix** [comment]
Okay check your tg

**Pull request merged**
