### PR TITLE
tissot: Change Maintainer (24/12/2018)

### PR DESCRIPTION
**Pull request by Abhinavgupta371**

### CODE REVIEW

**Comment by Subinsmani** [comment]
@Abhinavgupta371 lol tu bi aja abbb .

**Comment by Abhinavgupta371** [comment]
@Subinsmani kinda .

**Comment by Hasaber8** [comment]
@Abhinavgupta371 Saksham is also applying

**Comment by Abhinavgupta371** [comment]
@Hasaber8 ain't aware.. Anyways let Henrique device no mess peace ✌️

**Comment by Hasaber8** [comment]
@Abhinavgupta371 Ya last call is always from Henri.

**Comment by Abhinavgupta371** [comment]
@Hasaber8 yes ofc

**Comment by Hlcpereira** [comment]
@Abhinavgupta371 VoLIT icon when?

**Comment by PIPIPIG233666** [comment]
@Hlcpereira never lel

**Comment by Abhinavgupta371** [comment]
@Hlcpereira never better use subs

**Comment by divadsn** [comment]
@Abhinavgupta371 But bro volte

**Comment by Abhinavgupta371** [comment]
@divadsn volte already there in ims for icon go crie in corner plox ._.

**Comment by divadsn** [comment]
@Abhinavgupta371 i will hax your ims to minimize

**Comment by Abhinavgupta371** [comment]
@divadsn noi

**Comment by divadsn** [comment]
@Abhinavgupta371 *boi

**Comment by Hasaber8** [comment]
@Abhinavgupta371 Stap now

**Comment by Abhinavgupta371** [comment]
@Hasaber8 ohk sir

**Pull request merged**
