### PR TITLE
Add OnePlus 5T (dumpling)

### PR DESCRIPTION
**Pull request by itsjoeoui**

### CODE REVIEW

**Comment by itsjoeoui** [comment]
I already filled the form :)))

**Comment by shreejoy** [comment]
@xiaowyyyyya We are reviewing it

**Comment by Hlcpereira** [comment]
Far enough, and everything is fine, but yet there's some points related with the common-tree (some of my fault when I was maintaining OP5/5T) and now with the new rules to fit in it. Other than that it's approved your application for dumpling.

**Comment by itsjoeoui** [comment]
> Far enough, and everything is fine, but yet there's some points related with the common-tree (some of my fault when I was maintaining OP5/5T) and now with the new rules to fit in it. Other than that it's approved your application for dumpling.

Thank you, sir, very nice to see your reply!

**Comment by itsjoeoui** [comment]
Google Chrome 2019-08-13 at 10 50 13@2x
I just build another one

**Comment by itsjoeoui** [comment]
I have it ready to upload

**Comment by Hlcpereira** [comment]
Those must be reverted: 
https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/097ca20ab451527e28857cc2e03bfb6a790fa8e8
https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/909800653d2cca80ea1d9b47fbe2cd2cc56c63f6

The Playground must be also removed, yet the ARCore flag is fine to keep. 
Also I recommend the update of build description of init_oneplus_msm8998.cpp with the lastest build description value for dumpling and cheeseburger according to LineageOS tree.

Once those done your PR will be merged.

**Comment by itsjoeoui** [comment]
> Those must be reverted:
> [PixelExperience-Devices/device_oneplus_msm8998-common@097ca20](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/097ca20ab451527e28857cc2e03bfb6a790fa8e8)
> [PixelExperience-Devices/device_oneplus_msm8998-common@9098006](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/909800653d2cca80ea1d9b47fbe2cd2cc56c63f6)
> 
> The Playground must be also removed, yet the ARCore flag is fine to keep.
> Also I recommend the update of build description of init_oneplus_msm8998.cpp with the lastest build description value for dumpling and cheeseburger according to LineageOS tree.
> 
> Once those done your PR will be merged.

Okay will do it now

**Comment by SlackerState** [comment]
@Hlcpereira hey bro，can you check my pr ，plz

**Comment by itsjoeoui** [comment]
> Those must be reverted:
> [PixelExperience-Devices/device_oneplus_msm8998-common@097ca20](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/097ca20ab451527e28857cc2e03bfb6a790fa8e8)
> [PixelExperience-Devices/device_oneplus_msm8998-common@9098006](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/909800653d2cca80ea1d9b47fbe2cd2cc56c63f6)
> 
> The Playground must be also removed, yet the ARCore flag is fine to keep.
> Also I recommend the update of build description of init_oneplus_msm8998.cpp with the lastest build description value for dumpling and cheeseburger according to LineageOS tree.
> 
> Once those done your PR will be merged.

There two commits are reverted, and I checked with Los that the build description is already updated! :)))

**Comment by itsjoeoui** [comment]
> Those must be reverted:
> [PixelExperience-Devices/device_oneplus_msm8998-common@097ca20](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/097ca20ab451527e28857cc2e03bfb6a790fa8e8)
> [PixelExperience-Devices/device_oneplus_msm8998-common@9098006](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/commit/909800653d2cca80ea1d9b47fbe2cd2cc56c63f6)
> 
> The Playground must be also removed, yet the ARCore flag is fine to keep.
> Also I recommend the update of build description of init_oneplus_msm8998.cpp with the lastest build description value for dumpling and cheeseburger according to LineageOS tree.
> 
> Once those done your PR will be merged.

Playground is removed as well

**Pull request merged**
