### PR TITLE
Bring up Nokia 6.1 Plus

### PR DESCRIPTION
**Pull request by RaghuVarma331**
Well sorry for the inconvenience caused by morning from my side. as you can check my device tree which is in source code section now I divided in  to the respective sources with proper authorships . from my side iam done 

Thank you

### CODE REVIEW

**Comment by Subinsmani** [comment]
@RaghuVarma331 we need some more time to review your applications. We will notify you once it done. Thanks

**Comment by RaghuVarma331** [comment]
Thank you

**Comment by Subinsmani** [comment]
Hey @RaghuVarma331 Will you please update your thread with our latest official Pixel Experience thread style. Here you will found the thread template:- https://github.com/PixelExperience/docs/blob/pie/XDA_ThreadTemplate.txt
When its Done, ping us on this conversation.

Thank You
Regards
Subins

**Comment by RaghuVarma331** [comment]
Sure thanks

**Comment by RaghuVarma331** [comment]
@Subinsmani As per the  rules i updated the thread with the latest official pixel experience thread style. 
You can have a look now. 
https://forum.xda-developers.com/nokia-6-1-plus/development/rom-pixel-experiance-t3898527

Thank you
Regards
Raghu Varma

**Pull request merged**
