### PR TITLE
devices.json:add wayne

### PR DESCRIPTION
**Pull request by PIPIPIG233666**
device tree:https://github.com/PIPIPIG233666/android_device_xiaomi_wayne

### CODE REVIEW

**Comment by jhenrique09** [comment]
We're migrating website, please wait

**Comment by jhenrique09** [comment]
Contact me on tg

**Comment by PIPIPIG233666** [comment]
OK

**Comment by PIPIPIG233666** [comment]
wait plz

**Comment by PIPIPIG233666** [comment]
My tg is PIPIPIG233666

**Pull request merged**
