### PR TITLE
images: Updated mido's image

### PR DESCRIPTION
**Pull request by OccupationalTern**
Checked.

### CODE REVIEW

**Comment by baalajimaestro** [comment]
This is Pixel CI Automation Service! This PR has been closed as it has a derped devices.json and/or you are PR-ing some other file. Please recheck your PR.

**Comment by baalajimaestro** [comment]
Ignore the error, Ill pick your commit later.

**Comment by OccupationalTern** [comment]
I have checked the PR. It is only changing mido's image.

**Comment by OccupationalTern** [comment]
Fine and thanks!

**Comment by OccupationalTern** [comment]
The said commit hasn't been merged yet. Can you please merge it?

**Pull request closed without merging**
