### PR TITLE
Alex is stupid nigger

### PR DESCRIPTION
**Pull request by PDWarrior**
IMG_20200211_231746_167
@Mazda--

### CODE REVIEW

**Comment by baalajimaestro** [comment]
This is Pixel CI Automation Service! This PR has been closed as it has a derped devices.json and/or you are PR-ing some other file. Please recheck your PR.

**Comment by PDWarrior** [comment]
Nigga

**Comment by shreejoy** [comment]
Are you jobless?
Like nothing to do?

**Comment by baalajimaestro** [comment]
Kek max

**Pull request closed without merging**
