### PR TITLE
Request for adding c106

### PR DESCRIPTION
**Pull request by arnb70**

### CODE REVIEW

**Comment by Hlcpereira** [comment]
Hello sir. Thanks for applying. Anyway I'm sorry to tell that your application is been rejected because of the following reasons:

1 - Not maintaining unofficially for two weeks (That's why we request the Forum Thread)
2 - The commit history of your tree doesn't seems right, more like a kang fest than everything. 
3 - Your modificiations on the device tree seems to be done using Github web UI, which is not showing any skills with Git tool.

Once those point improved/solved, you can reapply once again.
Thanks for the comprehension and best regards.

**Comment by SlackerState** [comment]
@Hlcpereira hey bro，can you check my PR，Thanks

**Comment by arnb70** [comment]
Thanks for reviewing, i will try again after I solved those mentioned issues.

**Comment by shreejoy** [comment]
Next time make one commit PR 

They way you did was not even acceptable.

**Comment by arnb70** [comment]
I will try to full fill all requirements next time as you described. Thanks
for checking and giving some response.

**Comment by arnb70** [comment]
Sir, I have one question if I fork one of our device dev's device tree and
make required changes, is that device tree will be acceptable?

**Pull request closed without merging**
