### PR TITLE
add markw to official

### PR DESCRIPTION
**Pull request by Granrage**

### CODE REVIEW

**Comment by shreejoy** [comment]
@Granrage Bro I think you should not add the build now 

Once you join us then add the build

**Comment by Granrage** [comment]
@shreejoy Sorry, I just not fully understand how it's working here, so I only need to add device to devices.json ?

**Comment by shreejoy** [comment]
@Granrage Yes also why you added unofficial build 😅

**Comment by Granrage** [comment]
@shreejoy I don't know)

**Pull request merged**
