### PR TITLE
add nx563j as offical

### PR DESCRIPTION
**Pull request by RuRuTiaSaMa**

### CODE REVIEW

**Comment by RuRuTiaSaMa** [comment]
@jhenrique09 @Subinsmani accept please

**Comment by Subinsmani** [comment]
@RuRuTiaSaMa audio issue fixed?

**Comment by RuRuTiaSaMa** [comment]
> @RuRuTiaSaMa audio issue fixed?
fixed yesterday

**Comment by Subinsmani** [comment]
@RuRuTiaSaMa Didnt see anyone reporting Audio issue fixed or any new unofficial fixed build in xda...

**Comment by RuRuTiaSaMa** [comment]
> @RuRuTiaSaMa Didnt see anyone reporting Audio issue fixed or any new unofficial fixed build in xda...

ok,I'll upload a new build in mega,just a xml file changed_(:з」∠)_

**Comment by RuRuTiaSaMa** [comment]
@Subinsmani @jhenrique09  I uploaded a fix build just now,shall it be accepted now？

**Comment by jhenrique09** [comment]
Contact me on telegram

**Pull request merged**
