### PR TITLE
PixelExperience : Drop Mi A2

### PR DESCRIPTION
**Pull request by YashrajJadhav**
Due to the release of 13/02/2020 where all the sensors for the device were broken, then the quote by aryan where he said "I don't support wired headphones" (Which you can see here https://imgur.com/IQ2WnRH and here https://t.me/pixeljasmine/44603) I think that he doesn't deserve to be the maintainer of PixelExperience. Also OTA Updates aren't working which is a big issue for people who aren't rooted and for people who don't have TWRP Installed. And then there's the issue of phone's getting stuck with the data corrupt error.

### CODE REVIEW

**Comment by shreejoy** [comment]
Well this goes my last warning, don't try to act smart infront of us. If we heard of anything against maintainer, we have our policies to handle the situation. So you better not do this stuff again

**Comment by YashrajJadhav** [comment]
I was just trying to report some bugs which when I reported to the maintainer he didn't reply.

**Comment by shreejoy** [comment]
> I was just trying to report some bugs which when I reported to the maintainer he didn't reply.

Oh so in your view, impersonating some guy and making a straight pull request to remove the maintainer and drop the device is the correct way. Ah I must not be updated with latest fashion to report a bug. Till now I thought contacting some head of the team with some proper logs was the correct way.

**Comment by YashrajJadhav** [comment]
I already did that but didn't receive any response

**Comment by YashrajJadhav** [comment]
Can I pm you on Telegram about this?

**Comment by shreejoy** [comment]
> Can I pm you on Telegram about this?

Definitely after this event, you can't PM me on telegram. If you have something to say then we have provided a telegram group. You can use that.

**Pull request closed without merging**
