### PR TITLE
i9100: June update

### PR DESCRIPTION
**Pull request by linusdan**

### CODE REVIEW

**Comment by Subinsmani** [comment]
What the fucking hell, Recreate the PR again.

**Comment by KakatkarAkshay** [comment]
@Subinsmani 😂😂😂😂

**Comment by schneider94** [comment]
@Subinsmani LMAO

**Comment by linusdan** [comment]
@Subinsmani WTF aaaaaaaa HAHAHAHA

**Comment by Dyneteve** [comment]
@linusdan Update Drop
Replacement - May
June Update
Nudes when?

**Comment by KakatkarAkshay** [comment]
@linusdan Why everyone tagging Subinsmani?

**Comment by Hasaber8** [comment]
@Subinsmani Cause this message By him

**Comment by Dyneteve** [comment]
@Subinsmani Tag tag

**Pull request closed without merging**
