### PR TITLE
angler: bring it back

### PR DESCRIPTION
**Pull request by PixelBoot**
Reconsider it.

### CODE REVIEW

**Comment by shreejoy** [comment]
Sorry bro, as per our official devices documentations, you should test every build properly before testing. And you broke this rule for more than 3 times. So we cannot continue to allow the official support for angler.

**Review by shreejoy — COMMENTED** [review]
I have mentioned the reason above for the dis approval and it's a no from me.

**Comment by PixelBoot** [comment]
> Sorry bro, as per our official devices documentations, you should test every build properly before testing. And you broke this rule for more than 3 times. So we cannot continue to allow the official support for angler.

The latest builds from angler are fully functional. Tested and functional. Never heard of this 3 time rule either.

**Comment by shreejoy** [comment]
https://github.com/PixelExperience/docs/blob/master/maintainers_code_of_conduct.md

As per maintainers code of conduct. Each and every build should be throughly tested before release. But it's more than one time and as per other team members count it's all total three times you broke this single rule. So sorry, Maybe you can comeback later with some other device but not this time atleast with angler

**Pull request closed without merging**
