### PR TITLE
README.md reworded

### PR DESCRIPTION
**Pull request by aecarvalho**
Just a few grammatical changes

### CODE REVIEW

**Comment by baalajimaestro** [comment]
This is Pixel CI Automation Service! This PR has been closed as it has a derped devices.json and/or you are PR-ing some other file. Please recheck your PR.

**Comment by baalajimaestro** [comment]
This is Pixel CI Automation Service! This PR has been closed as it has a derped devices.json and/or you are PR-ing some other file. Please recheck your PR.

**Comment by aecarvalho** [comment]
Wait so how exactly do I correct the grammatical errors otherwise? I'm new to git so please assist

**Comment by ghost** [comment]
> Wait so how exactly do I correct the grammatical errors otherwise? I'm new to git so please assist

You should wait for someone to force push this commit.

**Comment by aecarvalho** [comment]
Thank you

**Pull request merged**
