### PR TITLE
add devices.json for cheeseburger and dumpling  OnePlus5/5T

### PR DESCRIPTION
**Pull request by SlackerState**
cheeseburger and dumpling

### CODE REVIEW

**Comment by Subinsmani** [comment]
Make proper Patch forst then do Pull Request Again.

**Comment by Subinsmani** [comment]
Make proper Patch first then do Pull Request Again.

**Comment by SlackerState** [comment]
@Subinsmani what does this mean

**Comment by Subinsmani** [comment]
Will You Explain What is this?

https://ibb.co/pw6d4W6

**Comment by SlackerState** [comment]
@Subinsmani I submitted a maintenance request for both devices,and the json is not wrong:flushed:

**Comment by Subinsmani** [comment]
@SlackerState each pull Request only one device allowed. and for every device you have to fill saperate Maintainership form also.

**Comment by SlackerState** [comment]
@Subinsmani OK，i will do pull Request again，I have filled in two forms. thanks:smile:

**Pull request closed without merging**
