### PR TITLE
Again support 6T

### PR DESCRIPTION
**Pull request by Saksham033**
This time no joke.!😂

### CODE REVIEW

**Comment by Dyneteve** [comment]
@Saksham033 no its meme now

**Comment by Manish4586** [comment]
@Saksham033 Cooool.. hmmmmmzzzzzzzz

**Comment by Saksham033** [comment]
@Saksham033 @Hlcpereira merge

**Comment by Dyneteve** [comment]
@Saksham033 maibi ye maibi not

**Comment by jhenrique09** [comment]
if you fail with this, it's the end, i warned.

**Comment by ZJRDroid** [comment]
@jhenrique09

**Pull request merged**
