### PR TITLE
X00TD maintainer change

### PR DESCRIPTION
**Pull request by LordShenron**

### CODE REVIEW

**Comment by SagarMakhar** [comment]
@LordShenron @jhenrique09 don't

**Comment by SunnyRaj84348** [comment]
@LordShenron wew

**Comment by AmanShettyA** [comment]
+1 I support. Give maintainership for LordShenron.

**Comment by ghost** [comment]
I support you bro. @jhenrique09 Give PE maintainership to @LordShenron

**Comment by Subinsmani** [comment]
@AmanShettyA Bring Zenmotion first lol

**Comment by krasCGQ** [comment]
@AmanShettyA joined GitHub just to comment "I support you"? What a joke.

**Comment by Panchajanya1999** [comment]
Lol, 
U want maintainership?
No no no.... I can estimate the future of the device,
Lord, help me

**Comment by LordShenron** [comment]
Guys stop spamming my PR, 
;_;

**Comment by ghost** [comment]
@kracsCGQ spammers from that fake group, wew😂

**Comment by krasCGQ** [comment]
@AmanShettyA I'm not spammer that you jerk off into everyday. Get your brain calibrated.

**Comment by Panchajanya1999** [comment]
Krascgq is a spammer??
Lord , take me , I can't see this

**Comment by LordShenron** [comment]
Amanshetty fool -_- 
Guys stop now please

**Comment by Panchajanya1999** [comment]
@jhenrique09
We, users don't want this guy a maintainer of PE for the device I work on,

**Comment by SunnyRaj84348** [comment]
When unofficial build sars ;__;

**Comment by ghost** [comment]
@jhenrique09

Sir, Please give maintainership to @LordShenron

**Comment by Subinsmani** [comment]
@AmanShettyA Due to ur misbehave he is not going to give any maintainership....
Now go and find another job...

**Comment by Orgasmtron** [comment]
WeW Pru Debs from wannabe official applying for official lulz...

**Comment by dev-harsh1998** [comment]
@krasCGQ Bro what the fuck in this world is happening here?

**Comment by ironmerc** [comment]
PE: Am I a joke to u ?

**Comment by SunnyRaj84348** [comment]
Lmao

**Comment by Toymakerftw** [comment]
Mittal sending reinforcement. 🤣

**Comment by ghost** [comment]
Who the hell is this Deepak Bhai?
And why is krascgq being targeted on telegram right after this?

**Pull request closed without merging**
