### PR TITLE
android_xiaomi_hydrogen

### PR DESCRIPTION
**Pull request by ghost**
new aosp_pie pixel experience for mi max

### CODE REVIEW

**Comment by jhenrique09** [comment]
?

**Comment by imsk17** [comment]
@VamsiKrishna999 U Didn't Make! If U did, u should have known how to upload to a repository.

**Comment by VamsiKrishna999** [comment]
I have done making device tree for mi max hydrogen and how to upload please
tell me

**Comment by VamsiKrishna999** [comment]
hydrogen proprietary
[proprietary-files.txt](https://github.com/PixelExperience/official_devices/files/2583763/proprietary-files.txt)

**Comment by baalajimaestro** [comment]
Wow man. DT in 1 commit. Seriously custom rom community was looking for people like you!

**Comment by SunnyRaj84348** [comment]
@baalajimaestro Silence plox

Sometime happens for newbies

**Comment by VamsiKrishna999** [comment]
Please can any one tell how to upload device tree into pixel experience
repository

**Comment by baalajimaestro** [comment]
This isn't the right place to ask I feel

**Comment by Hasaber8** [comment]
Boi to make a ROM you don't need to upload the device tree to repo.

**Comment by Hasaber8** [comment]
https://forum.xda-developers.com/chef-central/android/guide-how-to-build-rom-using-phone-t3727443
Use this thread make a unofficial ROM, test it, and then make a official ROM and please delete the PR and stop irritating everyone.

**Pull request closed without merging**
