### PR TITLE
Add clover

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
https://github.com/mamarama9904/android_device_xiaomi_clover

**Comment by AmanSinghRevenge** [comment]
Give Our Money back you Begger madarchod Bhosidike. Nalle k Kuthe. Uss Paisa Apna Ammi ko chod de Bhosidike. If you dont give Whyred Caf give money back madarchod. Bikari.

All @admin madrchod gandu bhousadi jhenrique09 kuta ka billa international begger.

**Comment by AmanSinghRevenge** [comment]
Give Our Money back you Begger madarchod Bhosidike. Nalle k Kuthe. Uss Paisa Apna Ammi ko chod de Bhosidike. If you dont give Whyred Caf give money back madarchod. Bikari.

All @admin madrchod gandu bhousadi jhenrique09 kuta ka billa international begger.

**Comment by AmanSinghRevenge** [comment]
Give Our Money back you Begger madarchod Bhosidike. Nalle k Kuthe. Uss Paisa Apna Ammi ko chod de Bhosidike. If you dont give Whyred Caf give money back madarchod. Bikari.

All @admin madrchod gandu bhousadi jhenrique09 kuta ka billa international begger.

**Comment by AmanSinghRevenge** [comment]
Give Our Money back you Begger madarchod Bhosidike. Nalle k Kuthe. Uss Paisa Apna Ammi ko chod de Bhosidike. If you dont give Whyred Caf give money back madarchod. Bikari.

All @admin madrchod gandu bhousadi jhenrique09 kuta ka billa international begger.

**Comment by ghost** [comment]
when can I make clover official?

**Pull request closed without merging**
