### PR TITLE
lavender: OTA 2019-08-08

### PR DESCRIPTION
**Pull request by nunocodex**

### CODE REVIEW

**Comment by shreejoy** [comment]
@nunocodex Wait for August patch

**Comment by Ashnetn** [comment]
When will August patch come ?

**Comment by markakash** [comment]
@Ashnetn Why won't it come?🤣

**Comment by nunocodex** [comment]
> @nunocodex Wait for August patch

I can't waiting, after i push another OTA simple.

**Comment by shreejoy** [comment]
@nunocodex Thing is we don't allow old patch in new month

**Pull request closed without merging**
