### PR TITLE
Update santoni maintainer

### PR DESCRIPTION
**Pull request by Dhruvgera**

### CODE REVIEW

**Comment by KakatkarAkshay** [comment]
@Dhruvgera You should know that @ErrorNetwork28 is not leaving AOSP Version before making pull request for Maintainer Change. Also fill the Maintainership form.

**Comment by schneider94** [comment]
Lmao. Fill out the form

**Comment by schneider94** [comment]
I do not leave with AOSP. Looooool. I’m just stopping сaf support

**Comment by Subinsmani** [comment]
Closing PR With these reasons:
1: He Made The PULL REQUEST for AOSP edition, where AOSP edition is still active.
2. He Gives Cerberus XDA instead of unofficial Pixel Experience Thread link.
3. With his Last Comment reason, this also proved that he didn't take time to read https://github.com/PixelExperience/official_devices readme file. where on 1.4 saying that "You must do an unofficial build for atleast 2 weeks, be sure that the build is stable for daily usage before applying. Stability context may differ for different devices, so explain for any exceptions."

Regards
Subins Mani

**Pull request closed without merging**
