### PR TITLE
Patch 9

### PR DESCRIPTION
**Pull request by shashankoooo999**
@jhenrique09 @Hlcpereira @Hasaber8 @baalajimaestro @Dyneteve @Abhinavgupta371 @SamarV-121 @Saksham033 @Jayant-Deshmukh @shreejoy @yashsonawane @coderzstas @Subinsmani @CryllicBuster273 @iamsaalim @bablusss @Akianonymus @ChaitanayaMittal @Chandra-Chaganti @darkbeast69 @ExpressLuke @ghostrider-reborn @Manish4586 @markakash @merothh @Nick-infinity @Orgasmtron @pqhaz @RandomRetard4676 @THLIVSQAZ @aswin7469 @AryanKedare @Ashwin4RC

### CODE REVIEW

**Comment by shashankoooo999** [comment]
@jhenrique09 @Hlcpereira @Hasaber8 @baalajimaestro @Dyneteve @Abhinavgupta371 @SamarV-121 @Saksham033 @Jayant-Deshmukh @shreejoy @yashsonawane @coderzstas @Subinsmani @CryllicBuster273 @iamsaalim @bablusss @Akianonymus @ChaitanayaMittal @Chandra-Chaganti @darkbeast69 @ExpressLuke @ghostrider-reborn @Manish4586 @markakash @merothh @Nick-infinity @Orgasmtron @pqhaz @RandomRetard4676 @THLIVSQAZ @aswin7469 @AryanKedare @Ashwin4RC

**Comment by shashankoooo999** [comment]
@jhenrique09 @Hlcpereira @Hasaber8 @baalajimaestro @Dyneteve @Abhinavgupta371 @SamarV-121 @Saksham033 @Jayant-Deshmukh @shreejoy @yashsonawane @coderzstas @Subinsmani @CryllicBuster273 @iamsaalim @bablusss @Akianonymus @ChaitanayaMittal @Chandra-Chaganti @darkbeast69 @ExpressLuke @ghostrider-reborn @Manish4586 @markakash @merothh @Nick-infinity @Orgasmtron @pqhaz @RandomRetard4676 @THLIVSQAZ @aswin7469 @AryanKedare @Ashwin4RC

**Comment by shashankoooo999** [comment]
@jhenrique09 @Hlcpereira @Hasaber8 @baalajimaestro @Dyneteve @Abhinavgupta371 @SamarV-121 @Saksham033 @Jayant-Deshmukh @shreejoy @yashsonawane @coderzstas @Subinsmani @CryllicBuster273 @iamsaalim @bablusss @Akianonymus @ChaitanayaMittal @Chandra-Chaganti @darkbeast69 @ExpressLuke @ghostrider-reborn @Manish4586 @markakash @merothh @Nick-infinity @Orgasmtron @pqhaz @RandomRetard4676 @THLIVSQAZ @aswin7469 @AryanKedare @Ashwin4RC

**Comment by Abhinavgupta371** [comment]
Aukat ma reh

**Comment by Subinsmani** [comment]
Abbe ye tho suaro ki tarah bacha paida kar raha hai with new pr pr, @shashank1436

**Comment by Subinsmani** [comment]
Abortion kab karega @shashank1436 didi?

**Comment by Subinsmani** [comment]
Desh me swine flu math badao, othewise your GF Corona will hit you.

**Comment by coderzstas** [comment]
Wtf with that guy ?

**Pull request closed without merging**
