### PR TITLE
Moto G5S Plus (Sanders)

### PR DESCRIPTION
**Pull request by Jorg3Lucas**

### CODE REVIEW

**Comment by ZJRDroid** [comment]
@jorgelucasd00 Buildbot detected

**Comment by yashsonawane** [comment]
@jorgelucasd00 Fuck

**Comment by Abhinavgupta371** [comment]
@jorgelucasd00 Nouuuu

**Comment by AryanKedare** [comment]
@jorgelucasd00 Bholte working?

**Comment by Hlcpereira** [comment]
@jorgelucasd00 Buildbot spotted

**Comment by Abhinavgupta371** [comment]
@Hlcpereira X2

**Comment by andersonmendess** [comment]
@jorgelucasd00 sandro plox

**Comment by Subinsmani** [comment]
@jorgelucasd00 what happens to ur xda thread, breakup with u or what?

**Comment by Jorg3Lucas** [comment]
> @jorgelucasd00 Bholte working?

Yes

**Comment by Jorg3Lucas** [comment]
> @jorgelucasd00 Bholte working?

Bholte, FM, DTV etc

**Comment by Subinsmani** [comment]
@jorgelucasd00 show us bholte logo

**Comment by AryanKedare** [comment]
@Subinsmani This is sed

**Comment by Hlcpereira** [comment]
@jorgelucasd00 Where is Bhilte?

**Comment by Jorg3Lucas** [comment]
> @jorgelucasd00 Buildbot spotted

sud

**Pull request closed without merging**
