### PR TITLE
Add back tulip

### PR DESCRIPTION
**Pull request by Saksham033**

### CODE REVIEW

**Comment by shreejoy** [comment]
@Saksham033 @ Everyone

**Comment by Hasaber8** [comment]
@Saksham033 Don't accept

**Comment by AryanKedare** [comment]
@Hasaber8 Sed

**Comment by SunnyRaj84348** [comment]
@Saksham033 We don't want conflicts again xD

**Comment by PIPIPIG233666** [comment]
@Saksham033 comon

**Comment by AryanKedare** [comment]
@Hasaber8 😂

**Comment by Abhinavgupta371** [comment]
@Saksham033 Rip 👌

**Comment by shreejoy** [comment]
@AryanKedare @jhenrique09 sir 😂

**Comment by Hasaber8** [comment]
@Saksham033 Until exams finish.

**Comment by ghost** [comment]
@Abhinavgupta371 you have boards. Study pls.

**Comment by Abhinavgupta371** [comment]
@Saksham033 Don't teach me kiddo

**Comment by shreejoy** [comment]
@Saksham033 🤣🤣🤣🤣

**Comment by EnesSastim** [comment]
@Saksham033 OOF

**Comment by Abhinavgupta371** [comment]
@Saksham033 Me aki shreejoy rohan arya have boards kthnx

**Comment by ghost** [comment]
Seems you're too big abhinav😆 😂 "How Fix bt"

**Comment by ghost** [comment]
Then study. Don't interfere

**Comment by Abhinavgupta371** [comment]
@Saksham033 Haha it's github or else i would have banged u up 👌

**Comment by EnesSastim** [comment]
@Saksham033 Well ur commit is wrong, check it

**Comment by ghost** [comment]
Oof! Gay🤣

**Comment by AryanKedare** [comment]
@shreejoy was already doing tulip ig

**Comment by shreejoy** [comment]
@AryanKedare TF where?

**Comment by AryanKedare** [comment]
@shreejoy 
sad my bad i got confused with redmi 6 pro and note 6 pro

**Comment by shreejoy** [comment]
@Saksham033 By abhinavagrd_1129:
Maybe he start a new project call PixelExperience-Kang edition 
🤣🤣🤣

**Comment by ghost** [comment]
@shreejoy you want abhinav's kang list?😂😂

**Comment by ghost** [comment]
Kanged fix by rupansh 
https://github.com/Abhinavgupta371/android_strix_xiaomi_tissot/commit/3c6b537e21b9876b22952fd743f44bb0d36e2668#commitcomment-31353586

Later gave authorship
https://mega.nz/#F!nCAT3IJQ!vPxARytRA-WFYV8fz1F_Zg

Kindly open and see :-)

**Pull request closed without merging**
