### PR TITLE
bring up oneplus5

### PR DESCRIPTION
**Pull request by SlackerState**
bring up oneplus5 back

### CODE REVIEW

**Comment by Subinsmani** [comment]
First Make the XDA thread with our proper template. Here is link https://github.com/PixelExperience/docs/blob/pie/XDA_ThreadTemplate.txt

 Once done let us know to check next steps.

**Comment by SlackerState** [comment]
> First Make the XDA thread with our proper template. Here is link https://github.com/PixelExperience/docs/blob/pie/XDA_ThreadTemplate.txt
> 
> Once done let us know to check next steps.

Thank you, I just completed the modification of the XDA thread, you can check it out.

**Comment by SlackerState** [comment]
@Subinsmani As per the rules i updated the thread with the latest official pixel experience thread style.
You can have a look now.
https://forum.xda-developers.com/oneplus-5/how-to/rom-pixel-experience-t3946026

Thank you

**Comment by Subinsmani** [comment]
Lamo I see users reporting download link issue on your thread, and it seems you are not either responding or not even fix the download link of your unofficial build, Its seems like no responsibility at all. however we will monitor your tgread for some more weeks and we also want to see your own git tree with updated one.. currently you gave old tree link. So please consider this remarks and again apply for official maintainership after 3 weeks.

Remember we need your own tree whether it is fork from anywhere, we want to see your own contribution on source. 

Thank You
Reagrds
Subins Mani

**Comment by SlackerState** [comment]
@Subinsmani what？i fix it ，You told me to change to your format, so the download link is also yours.

**Comment by SlackerState** [comment]
@Subinsmani what do you want？

**Comment by SlackerState** [comment]
@Subinsmani I am not responsible?  Take a good look at what you did yesterday.

**Comment by SlackerState** [comment]
@Subinsmani The tree is in my library, the table is a long time ago.

**Comment by Subinsmani** [comment]
@SlackerState my main thing to rejection is with your tree.. there is 0 contribution from you. We want maintainer not robot. So show your work rather then giving old tree which is already in pixel experience official org.

**Comment by SlackerState** [comment]
@Subinsmani Ok, I accept this.

**Pull request closed without merging**
