### PR TITLE
jasmine_sprout : maintainer update

### PR DESCRIPTION
**Pull request by Manish4586**

### CODE REVIEW

**Comment by jhenrique09** [comment]
Is that codename right? I mean, your main make file is called aosp_jasmine_sprout? This seems weird

**Comment by Manish4586** [comment]
Yes rebranded it from jasmine to jasmine_sprout

**Comment by ghostrider-reborn** [comment]
@Manish4586

**Comment by jhenrique09** [comment]
Sure

**Comment by Manish4586** [comment]
https://github.com/xiaomi-sdm660/android_device_xiaomi_jasmine_sprout/commit/7cec4a7106a6640b1892354ce24a4eaf4d69dd31

**Comment by Manish4586** [comment]
> @Manish4586

Yes

**Comment by rk779** [comment]
@Manish4586 lol

**Pull request merged**
