### PR TITLE
official_devices: Drop lavender & platina

### PR DESCRIPTION
**Pull request by AaradhayVijay**

### CODE REVIEW

**Comment by NotWeebDemon** [comment]
outstanding move vijay. i can't explain my happiness.
you deserve to be hated. you lied on telegram that you are dropping but the reality is i think the team kicked you because you are nonsense and we get better maintainer then you.
people like you should die you don't deserve anything.
you don't even deserve to live. you are a coward asshole.

**Comment by RisenID** [comment]
> outstanding move vijay. i can't explain my happiness. you deserve to be hated. you lied on telegram that you are dropping but the reality is i think the team kicked you because you are nonsense and we get better maintainer then you. people like you should die you don't deserve anything. you don't even deserve to live. you are a coward asshole.

Sir, with no due respect, please learn how pull requests work. He committed and opened it himself so how exactly do u explain that he was kicked? He left because of toxic idiots like you who have absolutely no knowledge or respect for people and yet are absolutely incompetent to do any dev work themselves. All of us do this work for free and as a hobby and if you are such an asshat and behave like this to your maintainers, why should they waste their time getting all this hate from idiots like you and apply for this position anyway? 

Anyway sorry I realise I used a lot of words and you probably didnt understand them [judging how absolutely smart your message here was (sarcasm)], so let me give you a tl;dr - 
"no u"

**Comment by NotWeebDemon** [comment]
> > outstanding move vijay. i can't explain my happiness. you deserve to be hated. you lied on telegram that you are dropping but the reality is i think the team kicked you because you are nonsense and we get better maintainer then you. people like you should die you don't deserve anything. you don't even deserve to live. you are a coward asshole.
> 
> Sir, with no due respect, please learn how pull requests work. He committed and opened it himself so how exactly do u explain that he was kicked? He left because of toxic idiots like you who have absolutely no knowledge or respect for people and yet are absolutely incompetent to do any dev work themselves. All of us do this work for free and as a hobby and if you are such an asshat and behave like this to your maintainers, why should they waste their time getting all this hate from idiots like you and apply for this position anyway?
> 
> Anyway sorry I realise I used a lot of words and you probably didnt understand them [judging how absolutely smart your message here was (sarcasm)], so let me give you a tl;dr - "no u"

But who asked him to maintain when he cannot fulfill his responsibility ? He drop in August and take back then in 2 days. Now this will happen again ? Pixel team allow this shit ?

**Comment by windowz414** [comment]
@NotWeebDemon, first of all, you're not allowed to comment on pull requests. Second of all, he wasn't kicked, he resigned himself. Third, I don't know what you guys are on but I won't let you guys do the same as what you guys did to my beloved one (Maybe you guys still remember her). Fourth, if you're that smart, then come try and maintain yourself. No one holds you.

Oh and, "who asked him to maintain" maintainers are done voluntarily without needing anyone ask him. Take me as example: I'm maintaining rosemary not because people asked but because I chose it. People come and go and you have no say on that. It's up to PE team to decide.

**Comment by herobuxx** [comment]
> > > outstanding move vijay. i can't explain my happiness. you deserve to be hated. you lied on telegram that you are dropping but the reality is i think the team kicked you because you are nonsense and we get better maintainer then you. people like you should die you don't deserve anything. you don't even deserve to live. you are a coward asshole.
> > 
> > 
> > Sir, with no due respect, please learn how pull requests work. He committed and opened it himself so how exactly do u explain that he was kicked? He left because of toxic idiots like you who have absolutely no knowledge or respect for people and yet are absolutely incompetent to do any dev work themselves. All of us do this work for free and as a hobby and if you are such an asshat and behave like this to your maintainers, why should they waste their time getting all this hate from idiots like you and apply for this position anyway?
> > Anyway sorry I realise I used a lot of words and you probably didnt understand them [judging how absolutely smart your message here was (sarcasm)], so let me give you a tl;dr - "no u"
> 
> But who asked him to maintain when he cannot fulfill his responsibility ? He drop in August and take back then in 2 days. Now this will happen again ? Pixel team allow this shit ?

1. He completed all requirement to maintain PE for your device
2. There is a reason behind he is leaving and back in 2 days that Core team understand and approved, while you know nothing and just bossing us around like u paid the whole team and maintainer to do the thing you want. No, once again we doing it's as a hobby and we committed to it. Stop being an asshole. If you think you more qualified for this, just apply and prove it. You're just yet another Karen who only able to complain but never do the shit.

**Comment by herobuxx** [comment]
Imagine creating an account an hour ago just to insult someone who really contributed to the community while you being a stupid asshole who just makes the community even worse. I think this is why he won't to continue PE for the device. You're just being too much. That makes dev won't contribute to the device anymore.

**Comment by NotWeebDemon** [comment]
Now i say i kill his family when he is not at house Tell what you will do.

**Comment by RisenID** [comment]
> Now i say i kill his family when he is not at house Tell what you will do.

Nothing because you dont know where he lives ?

**Comment by windowz414** [comment]
> Now i say i kill his family when he is not at house Tell what you will do.

@NotWeebDemon, thanks for the content to report. GitHub team will soon take action to warn you or terminate your account.

**Comment by NotWeebDemon** [comment]
> > Now i say i kill his family when he is not at house Tell what you will do.
> 
> @NotWeebDemon, thanks for the content to report. GitHub team will soon take action to warn you or terminate your account.

And what if he revert again. last time new maintainer application was cancel because of this reason. I want to sure that now if he revert it should not merge and new guy will be approved who apply. vijay don't own pixelexprince lavender.

**Comment by RisenID** [comment]
> > > Now i say i kill his family when he is not at house Tell what you will do.
> > 
> > 
> > @NotWeebDemon, thanks for the content to report. GitHub team will soon take action to warn you or terminate your account.
> 
> And what if he revert again. last time new maintainer application was cancel because of this reason. I want to sure that now if he revert it should not merge and new guy will be approved who apply. vijay don't own pixelexprince lavender.

You dont own pixelexprince lavender either. kbye

**Comment by windowz414** [comment]
*Aaaand, he still goes on.*

> vijay don't own pixelexprince lavender.

You don't own PixelExperience either.

**Comment by herobuxx** [comment]
> > > Now i say i kill his family when he is not at house Tell what you will do.
> > 
> > 
> > @NotWeebDemon, thanks for the content to report. GitHub team will soon take action to warn you or terminate your account.
> 
> And what if he revert again. last time new maintainer application was cancel because of this reason. I want to sure that now if he revert it should not merge and new guy will be approved who apply. vijay don't own pixelexprince lavender.

So what? If PE core team approved it, why not? What can you do? Why you bossing us around? Who do u think u are? What u have done to the community? Have you realized who you are in this life and the community? Are you a people with big influence? Do anyone else considered you as a normal humanbeing?

**Comment by windowz414** [comment]
Read: "I can't cope with all these people siding against me for being wrong. I go away."

**Comment by KakatkarAkshay** [comment]
That's enough drama for today. For more to to Netflix.

**Pull request merged**
