### PR TITLE
Adding oneplus2 to official list of devices

### PR DESCRIPTION
**Pull request by danny2895**

### CODE REVIEW

**Comment by danny2895** [comment]
Adding oneplus2 to official list of devices

**Comment by Hlcpereira** [comment]
@danny2895 Remove oneplus2.json for now

**Comment by danny2895** [comment]
okay , do i need to remove and again pull request ?

**Comment by shreejoy** [comment]
No need just remove those commits

**Comment by danny2895** [comment]
thanks , removed oneplus2.json
@Hlcpereira  @shreejoy

**Pull request merged**
