### PR TITLE
New Redmi 4A maintainer PE-CAF

### PR DESCRIPTION
**Pull request by koito97**

### CODE REVIEW

**Comment by Abhinavgupta371** [comment]
@dandyfarid Ig this is not allowed no separate maintainer for different versions

**Comment by koito97** [comment]
why not allowed sir ? :(

**Comment by Abhinavgupta371** [comment]
@dandyfarid My bad buddy it's allowed

**Comment by koito97** [comment]
so am I allowed, sir ?

**Comment by Subinsmani** [comment]
@dandyfarid if ur AOSP maintainer have no objection then u can..

**Comment by jhenrique09** [comment]
contact me on telegram

**Comment by koito97** [comment]
@jhenrique09 ok sir

**Pull request merged**
